version: '3'
services:
  postgres:
    image: postgres
    volumes:
       - db-data:/var/lib/postgresql/data
    ports: 
      - "49822:5432"
    environment:
      - POSTGRES_PASSWORD=url_root
      - POSTGRES_USER=postgres
  node:
    build: .
    ports:
      - "3000:3000"    
    links:
      - postgres
    depends_on:
      - postgres
volumes:
  db-data:
    driver: local
    